---
title: "Conversationla alignment in Autistic children"
author: "authors"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(stringr)
library(boot)
library(purrr)
library(ggplot2)
library(ggthemes)
library(feather)
library(poweRlaw)
library(wordbankr)
#library(rwebppl)
library(lme4)
library(lmerTest)
library(Hmisc)
library(qdapRegex)
library(HDInterval)

```

Data 

```{r}


#Nadig Data (with caregiver)

data_real_Nadig <- read.csv("ALIGN_results/Nadig/process/turns_Nadig.csv") %>%
  mutate(control = "real") 

data_surogate_Nadig <- read.csv("ALIGN_results/Nadig/process/turns_surogate_dyad_Nadig.csv") %>%
  mutate(control = "shuffled")

data_Nadig <- data_real_Nadig %>%
  bind_rows(data_surogate_Nadig) %>%
  mutate(corpus  = "Nadig")

#Eigsti Data (with experimenter)

data_real_Eigsti <- read.csv("ALIGN_results/Eigsti/process/turns_results_Eigsti.csv") %>%
  mutate(control = "real") 

data_surogate_Eigsti <- read.csv("ALIGN_results/Eigsti/process/turns_surogate_dyad_Eigsti.csv") %>%
  mutate(control = "shuffled")

data_Eigsti <- data_real_Eigsti %>%
  bind_rows(data_surogate_Eigsti) %>%
  mutate(corpus  = "Eigsti")

combined <- data_Nadig %>%
  bind_rows(data_Eigsti)

```

data_Nadig
```{r echo = FALSE, message=FALSE, warning=FALSE}

data_Nadig_model <- data_Nadig %>%
  #rename(condition = autistic.) %>%
  #filter(condition ==  'ASD' | condition == 'TYP') %>% 
  mutate(direction = if_else(str_detect(partner_direction, 'CHI>'), 'adult',
                             if_else(str_detect(partner_direction, '>CHI'), 'child', 
                                     'adult-adult'))) %>%
  filter(direction  != 'adult-adult') 
  
data_summary <- data_Nadig_model %>%
  gather(measure, value, syntax_penn_tok1:cosine_semanticL) %>%
  group_by(control, condition, direction, measure) %>%
  summarise(mean = mean(value, na.rm = T),
                   sd = sd(value, na.rm = T),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se) 

data_subset <- data_summary %>%
  filter(measure %in% c('cosine_semanticL', 'lexical_lem2', 'syntax_penn_lem2'))

ggplot(data_subset, aes(x = direction , y = mean, fill=condition)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_linerange(aes(ymin = lower, ymax = upper), 
                  position = position_dodge(width = .9), size = 0.6)+
  theme_few() +
  theme(aspect.ratio = 0.7, 
        axis.text=element_text(size=14, angle = 90),
        strip.text.x = element_text(size=10),
        strip.text.y = element_text(size=10),
        axis.title=element_text(size=16))+
  facet_grid(measure ~ control, scales = "free_y")

```

The statistical analyses for Nadig  (you can do the same for Eigsti)
```{r}

#Conceptual alignment

#To show the results for each model; use summary(name_of_the_model)

#Model 1: main effects of condition, direction and control on alignement
model_semantic <- lmer(cosine_semanticL ~  condition + direction + control + ( 1 | condition_info), data = data_Nadig_model )

##Results:  all these main effects are significant predictors of alignmnt


#Model 2: main effects of condition and control on children's alignemnt
model_semantic_ch <- lmer(cosine_semanticL ~  condition + control + ( 1 | condition_info), 
                          data = data_Nadig_model %>% filter(direction == "child"))
##Results: both are significant

#Model 3: effect of control for TYP (are they above chance?)
model_semantic_ch_typ <- lmer(cosine_semanticL ~  control + ( 1 | condition_info), 
                          data = data_Nadig_model %>% filter(direction == "child",
                                                             condition == "TYP"))
#Results : Yes

#Model 4: effect of control for ASD (are they above chance?)
model_semantic_ch_asd <- lmer(cosine_semanticL ~  control + ( 1 | condition_info), 
                          data = data_Nadig_model %>% filter(direction == "child",
                                                             condition == "ASD"))
#Results : Yes (this is a cool results!)


#Model 5  Here compare TYP vs. ASD only in the real conversation 
model_semantic_ch_real <- lmer(cosine_semanticL ~  condition + ( 1 | condition_info), 
                          data = data_Nadig_model %>% filter(direction == "child",
                                                             control == "real"))

#Results : Not significant (although it goes in the right direction, i.e., TYP > ASD). Mabybe this is due to the fact that we don't have enough data (low statistical power), so we combine both Nadig and Eigsti (see below)

```


The statistical analyses for the combined corpus (both Nadig and Eigsti), using this difference as a random effect in the models
```{r}

data_combined_model <- combined %>%
  #rename(condition = autistic.) %>%
  #filter(condition ==  'ASD' | condition == 'TYP') %>% 
  mutate(direction = if_else(str_detect(partner_direction, 'CHI>'), 'adult',
                             if_else(str_detect(partner_direction, '>CHI'), 'child', 
                                     'adult-adult'))) %>%
  filter(direction  != 'adult-adult') %>%
  filter(condition  != "DD")

#Model 6:  is there a significant difference between TYP vs. ASD only in the real conversation ?
model_semantic_ch_real <- lmer(cosine_semanticL ~  condition + ( 1 | condition_info) + ( 1 | corpus), 
                          data = data_combined_model %>% filter(direction == "child",
                                                             control == "real"))
#Results: No, but close enough. Since the difference is small, we probably need more data to test if the difference is significant

```


data_Eigsti
```{r echo = FALSE, message=FALSE, warning=FALSE}

data_Eigsti_model <- data_Eigsti %>%
  #rename(condition = autistic.) %>%
  #filter(condition ==  'ASD' | condition == 'TYP') %>% 
  mutate(direction = if_else(str_detect(partner_direction, 'CHI>'), 'adult',
                             if_else(str_detect(partner_direction, '>CHI'), 'child', 
                                     'adult-adult'))) %>%
  filter(direction  != 'adult-adult',
         condition != 'DD') 
  
  
data_summary <- data_Eigsti_model %>%
  #rename(condition = autistic.) %>%
  #filter(condition ==  'ASD' | condition == 'TYP') %>% 
  gather(measure, value, syntax_penn_tok1:cosine_semanticL) %>%
  mutate(direction = if_else(str_detect(partner_direction, 'CHI>'), 'adult', 'child')) %>%
  group_by(control, condition, direction, measure) %>%
  summarise(mean = mean(value, na.rm = T),
                   sd = sd(value, na.rm = T),
                   n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  select(-sd, -n, -se) 

data_subset <- data_summary %>%
  filter(measure %in% c('cosine_semanticL', 'lexical_lem2', 'syntax_penn_lem2'))

ggplot(data_subset, aes(x = direction , y = mean, fill=condition)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_linerange(aes(ymin = lower, ymax = upper), 
                  position = position_dodge(width = .9), size = 0.6)+
  theme_few() +
  theme(aspect.ratio = 0.7, 
        axis.text=element_text(size=14, angle = 90),
        strip.text.x = element_text(size=10),
        strip.text.y = element_text(size=10),
        axis.title=element_text(size=16))+
  facet_grid(measure ~ control, scales = "free_y")

```


```{r}

data_summary_2 <- data_summary %>%
  select(-lower, -upper) %>%
  spread(direction, mean) %>%
  mutate(child_adult = child - adult)


ggplot(data_summary_2, aes(x = condition, y = child_adult)) +
  geom_bar(stat="identity", position=position_dodge())+
  theme_few() +
  theme(aspect.ratio = 0.7, 
        axis.text=element_text(size=10, angle = 45),
        strip.text.x = element_text(size=10),
        strip.text.y = element_text(size=5),
        axis.title=element_text(size=16))+
  facet_wrap(~ measure)

```

```{r}

```

